ia_register:
    resource: "@IARegisterBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:          /user/login
    defaults:         { _controller: IARegisterBundle:User:login }

login_check:
    pattern:           /user/login_check

logout:
    pattern:           /user/logout