security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:             /user/login
                check_path:             /user/login_check
#                use_forward:            true

    access_control:
        - { path: ^/user/list, roles: ROLE_ADMIN }

    providers:
        main:
            entity:
                class:                  IA\RegisterBundle\Entity\User
                property:               username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        IA\RegisterBundle\Entity\User: sha512

#    access_control:
#        - { path: ^/backend/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: ROLE_USER }